### ISSUE TITLE
GPS OR NOTIFICATION

### ISSUE THREAD

**Issue by foregz** [Pyth3rEx/esx_fireDispatch#1]
is there anyway to add notification when a fired is started? like gps for the firejob

**Comment by Pyth3rEx** [comment]
Of course! I'm not working on this script anymore due to lack of support. If you guys *really* want it I can start working it again... maybe...

**Comment by foregz** [comment]
i strated working on a FD job on my server and this is the best fire script with the alarms and all that i really want this script to continue just with a gps fucntion and bigger fires it would be perfect :(

**Comment by Pyth3rEx** [comment]
Come talk to me in DMs on Discord: https://discord.gg/MpRfMf9
