### ISSUE TITLE
Changing the sound of the siren to custom sound. 

### ISSUE THREAD

**Issue by Sythy11** [Pyth3rEx/esx_fireDispatch#11]
Hi,

I am wanting to use the sirens from another script with your script, however it appears your script downloads a resource.rpf file each time it loads. This other script puts the mp3 files into a local directory. 

I have been looking through the code, and trying to merge the required parts. But I think it's the fact your script is getting that resource.rpf file. 

I have added the script I am wishing to come from. 

[Fire-EMS-Pager-9b43699f5de49ff720ed4f40aac0479744761bef.zip](https://github.com/Pyth3rEx/esx_fireDispatch/files/3705428/Fire-EMS-Pager-9b43699f5de49ff720ed4f40aac0479744761bef.zip)

**Comment by Pyth3rEx** [comment]
Hey, currently the script dosn't support custom sound as it uses a looping of a base game 'bip' sound I found in the game files. Might look into adding this in the future but I am not offering support for such feature for now, sorry.
