### ISSUE TITLE
Putting out the fire

### ISSUE THREAD

**Issue by nickb203** [Pyth3rEx/esx_fireDispatch#14]
I am not too sure if I am just missing something.  Are you suppose to be able to use a vehicle-mounted water cannon to put out the fires?  Or is it limited to just fire extinguishers?  Are you suppose to be able to use the water cannon?

**Comment by Pyth3rEx** [comment]
Basically 90% of the fire is particles to make it look good. You need to put out the 'script' fire. It's a tiny bit of 'real' fire at the base. removing that will remove the entire particle part.

**Comment by Kirito-Kirigaya-Kazuto** [comment]
Hello 
![image](https://user-images.githubusercontent.com/17107837/75396439-c3e43980-58f4-11ea-9ba0-8eab8256526f.png)

the fire refuses to go out after 3 minutes of water spray on it, moreover there is not really syncro

use ver : FRAMEWORK v1.3_f

Thx you

**Comment by Pyth3rEx** [comment]
Hey, did you make sure that you are spraying on the CENTER of the fire? see comment above.

**Comment by Kirito-Kirigaya-Kazuto** [comment]
Yes

**Comment by Kirito-Kirigaya-Kazuto** [comment]
local fireSpawnLocation = {
  { x = 1182.78, y = -1550.45, z = 40.59, name = "El Burro Station - Testing Fire 1", id = 1, isFuel = false}, --fire // id = type of fire
  { x = 1182.10, y = -1563.23, z = 40.40, name = "El Burro Station - Testing Fire 2", id = 1, isFuel = false}, --fire // id = type of fire
}

**Comment by Kirito-Kirigaya-Kazuto** [comment]
I am available on discord : *Kirito*#9256

**Comment by Kiltek** [comment]
I am having the same issue, I can not /stopFires or get rid of a fire that has started. Has this script been updated since March? with fixes
