### ISSUE TITLE
not getting notified of a fore

### ISSUE THREAD

**Issue by numpty9989** [Pyth3rEx/esx_fireDispatch#15]
**Describe the bug**

EMS/Fire are not getting notified when there is a fire Police are though

**To Reproduce**
Steps to reproduce the behaviour:
join the server as EMS/Fire wit minimum of 4 online (no message)
Join server as police (get notification)

**Expected behaviour**
EMS/Fire shud be the only ones notified

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Win 10
 - Browser [e.g. chrome, safari] Chrome

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] Samsung S10+
 - OS: [e.g. iOS8.1] Androis10
 - Browser [e.g. stock browser, safari] Chrome

**Additional context**

**Comment by Pyth3rEx** [comment]
Hey, the notification is in no way connected to the job, this is therefore an issue on your side. Furthermore the script is being rewritten in v2.0 and I will therefore not fix any more bugs in this version. Reopen if you still have questions.
