### ISSUE TITLE
FireDispatch  It does not work TriggerClientEvent

### ISSUE THREAD

**Issue by Netzwerk10** [Pyth3rEx/esx_fireDispatch#17]
Hello, I'm using your script on our server, but unfortunately it doesn't work. The following error message is displayed.

SCRIPT ERROR: @esx_fireDispatch/client/client.lua:15: attempt to call a nil value (global 'TriggerClientEvent')

What could be the problem? We would love to use the script. :)

Sorry for my Bad English, i come from Germany :)

**Comment by Pyth3rEx** [comment]
Sadly this script is on halt until I can find some way to rewrite it the way I want it. Which I don't have time for ;( your best bet would be to use an earlier version. Sorry
