### ISSUE TITLE
Resource loading for esx_fireDispatch failed

### ISSUE THREAD

**Issue by rencis** [Pyth3rEx/esx_fireDispatch#4]
I can't get it install, maybe this broke all "_ThingsForTheMachine	Probably broke everything"
Can you help me ? 
Maybe you can make some video how to install this resource ? 

Console said "Resource loading for esx_fireDispatch failed:"
IMG: https://i.postimg.cc/J0WywB3x/cant.jpg

**Comment by Pyth3rEx** [comment]
Are you using the latest stable [release](https://github.com/Pyth3rEx/esx_fireDispatch/releases) or did you just clone the files?

**Comment by rencis** [comment]
I use FRAMEWORK v1.1_f
Where i need put fireDispatch folder ? 
If i put the content of _ThingsForTheMachine into my [ESX] folder on your FiveM server where i need put that fireDispatch folder?

Maybe you can make some install video ?

**Comment by Pyth3rEx** [comment]
Install should look like this:
/root/resources/{ESX}/ESX_FireDispatch/server.lua

and so on...

**Comment by rencis** [comment]
Yeah i did it, then server.cfg "start ESX_FireDispatch", then i log in to my server and it show up a window with text "Resource loading for esx_fireDispatch failed:"

Add me on discord i will share my screen and i will show to you.
Discord Rencis#3225

**Comment by TomTom20002** [comment]
Could i have some help with the same problem, thank you

**Comment by Pyth3rEx** [comment]
I'm going to need need some logs guys, "Resource loading for esx_fireDispatch failed:" is not a valid error code.

**Comment by Pyth3rEx** [comment]
After screensharing with @rencis I can confirm this is a wrong install, not an issue with the script. Issue closed.

**Comment by rencis** [comment]
Thanks man, you are the best ! Rate * * * * * (Five stars xD)
