### ISSUE TITLE
Fire Spreading

### ISSUE THREAD

**Issue by Sythy11** [Pyth3rEx/esx_fireDispatch#5]
I am writing to you to see how you are getting fire to spread. I cant get it to spread at all.    The only thing I can get the script to do is spawn fires.   Not even remove them. 

I have just got a plain server with just ESX, vMenu, MySQL Async, and EssentialMode installed.

**Comment by Pyth3rEx** [comment]
You can remove fires but restarting the script or putting them out. Regarding the spreading this is an untested feature, it works theoreticaly tough. Can you provide a more complete bug report with context please?

P.S I just uploaded a new version a few hours ago, did you get it before posting this?

**Comment by Sythy11** [comment]
Yes I have updated the script. 

When I light the fire, it can sit there for however long it wants (even if I change the wait timer), in all that time it will not spread at all. It will just be that one tile which has fire.

**Comment by Pyth3rEx** [comment]
What wait timer are you talking about? Regarding the issue I'll have a look at it in tomorow night's stream

**Comment by Sythy11** [comment]
```
   -- Handeling spreading of fires
    Wait(10)
    if #scriptData.firePositionsX == 1 then
    else
```


I've changed it to 10 from 1000 because im impaitent.

**Comment by Pyth3rEx** [comment]
you just made the entire script update every 0,01 secon which could lead to huge issues such as hard crash. Don't do that.

**Comment by Sythy11** [comment]
Seeing as I had (almost) bare bones, it was running okay. The main devs for our server are going to work it into a proper dispatch system. But basing it off your script for the flames/smoke/blips.

**Comment by Pyth3rEx** [comment]
Just make sure your script follows the licence and you are fine ;) I wouldn't mind a credit tough :P

A proper dispatch system is in the works for the first non-framework update.

**Comment by Pyth3rEx** [comment]
So a little update: the fire spreading works but dosn't show. v1.3_f will include the spreading.
