### ISSUE TITLE
Fire spreading causes resource time error.

### ISSUE THREAD

**Issue by EastCoastModding** [Pyth3rEx/esx_fireDispatch#6]
Hello. There is a issue whenever we (my team) uses the script. Time after awhile when the fire spreads we all get a resource time warning and some of us lag out.

**Comment by Pyth3rEx** [comment]
Can you tell me how much it gets? (the values on the ressource warning). Weanwhile just use the latest stable release in the release tab

**Comment by EastCoastModding** [comment]
It says anywhere from 30-60 fps

**Comment by Pyth3rEx** [comment]
Issue will be fixed in next stable release ;)

**Comment by Pyth3rEx** [comment]
Issue seems fixed. Will be published on next stable release (1.3_f)
