### ISSUE TITLE
Random Fire not working

### ISSUE THREAD

**Issue by Seamus-McMasters** [Pyth3rEx/esx_fireDispatch#7]
So, I just put this in my server, pretty cool script Added it early in my server config as suggested in the ReadMe. I noticed the random fire functions in the script, is this expected to work, or is this still in Development?  I tired testing it with a 3000 ms time set in the config fire thinking i would see a bunch pop up quickly, nothing happened.

Also, I see the 2 test areas programmed in, will the random portion choose from this “local locations” section or will it random pull coords and create a fire?

**Comment by Pyth3rEx** [comment]
What version of the script are you using?

**Comment by Seamus-McMasters** [comment]
I would imagine the most recent version, the one linked in the FiveM Forums, I check the script and no version is listed.

**Comment by Pyth3rEx** [comment]
Please follow the install instructions and head to the [release](https://github.com/Pyth3rEx/esx_fireDispatch/releases) tab to download the latest STABLE version. (1.3_f today)

**Comment by Pyth3rEx** [comment]
No response - closing issue. Feel free to reopen it if you feel like I havn't answered it correctly.
